package gceirental;
// Generated 24/11/2011 19:23:00 by Hibernate Tools 3.2.1.GA



/**
 * EventId generated by hbm2java
 */
public class EventId  implements java.io.Serializable {


     private int eventid;
     private int userid;

    public EventId() {
    }

    public EventId(int eventid, int userid) {
       this.eventid = eventid;
       this.userid = userid;
    }
   
    public int getEventid() {
        return this.eventid;
    }
    
    public void setEventid(int eventid) {
        this.eventid = eventid;
    }
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventId) ) return false;
		 EventId castOther = ( EventId ) other; 
         
		 return (this.getEventid()==castOther.getEventid())
 && (this.getUserid()==castOther.getUserid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEventid();
         result = 37 * result + this.getUserid();
         return result;
   }   


}


