package gceirental;
// Generated 24/11/2011 19:23:00 by Hibernate Tools 3.2.1.GA



/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private EventId id;
     private String title;
     private String presentation;
     private String history;
     private String objective;
     private String themes;
     private String deadline;
     private String importantDates;
     private String schedule;
     private String organization;
     private String partners;

    public Event() {
    }

	
    public Event(EventId id) {
        this.id = id;
    }
    public Event(EventId id, String title, String presentation, String history, String objective, String themes, String deadline, String importantDates, String schedule, String organization, String partners) {
       this.id = id;
       this.title = title;
       this.presentation = presentation;
       this.history = history;
       this.objective = objective;
       this.themes = themes;
       this.deadline = deadline;
       this.importantDates = importantDates;
       this.schedule = schedule;
       this.organization = organization;
       this.partners = partners;
    }
   
    public EventId getId() {
        return this.id;
    }
    
    public void setId(EventId id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPresentation() {
        return this.presentation;
    }
    
    public void setPresentation(String presentation) {
        this.presentation = presentation;
    }
    public String getHistory() {
        return this.history;
    }
    
    public void setHistory(String history) {
        this.history = history;
    }
    public String getObjective() {
        return this.objective;
    }
    
    public void setObjective(String objective) {
        this.objective = objective;
    }
    public String getThemes() {
        return this.themes;
    }
    
    public void setThemes(String themes) {
        this.themes = themes;
    }
    public String getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(String deadline) {
        this.deadline = deadline;
    }
    public String getImportantDates() {
        return this.importantDates;
    }
    
    public void setImportantDates(String importantDates) {
        this.importantDates = importantDates;
    }
    public String getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public String getPartners() {
        return this.partners;
    }
    
    public void setPartners(String partners) {
        this.partners = partners;
    }




}


